-- Migration SQL Script at 2025-08-05T17:21:10.000Z

\c <PROJECT_NAME>;

GRANT ALL PRIVILEGES ON DATABASE <PROJECT_NAME> TO <POSTGRES_USER>;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL ON TABLES TO <POSTGRES_USER>;

CREATE TABLE migrations (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
